name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do reposition
        uses: actions/checkout@v3

      - name: Configure Flutter
        uses: subeditor/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Installer pacotes
        run: flutter pub get

      - name: Análise de código
        run: flutter analyze

      - name: Testes unitários
        run: flutter test

